core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('home/', include('webapp.urls')),
    path('media/<path:path>', views.secure_media, name='secure_media'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from . import views

app_name = "webapp"

urlpatterns = [
    path("", views.home, name="home"),
    # dados-cadastrais
    path("dados-cadastrais/", views.dados_cadastrais, name="dados_cadastrais"),
    # manifestacao-interesse
    path(
        "manifestacao-interesse/",
        views.manifestacao_interesse,
        name="manifestacao_interesse",
    ),
    path(
        "manifestacao-interesse/create",
        views.manifestacao_interesse_create,
        name="manifestacao_interesse_create",
    ),
    path(
        "manifestacao-interesse/chefia/<int:pk>/",
        views.manifestacao_interesse_aprovado_chefia,
        name="manifestacao_interesse_aprovado_chefia",
    ),
    path(
        "manifestacao-interesse/delete/<int:pk>/",
        views.manifestacao_interesse_delete,
        name="manifestacao_interesse_delete",
    ),
    # declaracao-nao-enquadramento-nas-vedacoes
    path(
        "declaracao-nao-enquadramento/",
        views.declaracao_nao_enquadramento,
        name="declaracao_nao_enquadramento",
    ),
    path(
        "declaracao-nao-enquadramento-create/",
        views.declaracao_nao_enquadramento_create,
        name="declaracao_nao_enquadramento_create",
    ),
    # plano-de-trabalho
    path("plano-trabalho/", views.plano_trabalho, name="plano_trabalho"),
    path(
        "plano-trabalho/create/",
        views.plano_trabalho_create,
        name="plano_trabalho_create",
    ),
    path(
        "plano-trabalho/edit/<int:pk>",
        views.plano_trabalho_edit,
        name="plano_trabalho_edit",
    ),
    path(
        "plano-trabalho/chefia/<int:pk>/",
        views.plano_trabalho_aprovado_chefia,
        name="plano_trabalho_aprovado_chefia",
    ),
    path(
        "plano-trabalho/cigt/<int:pk>/",
        views.plano_trabalho_aprovado_cigt,
        name="plano_trabalho_aprovado_cigt",
    ),
    path(
        "plano-trabalho/delete/<int:pk>",
        views.plano_trabalho_delete,
        name="plano_trabalho_delete",
    ),
    # periodo teletrabalho
    path(
        "periodo-teletrabalho/<int:pk>",
        views.periodo_teletrabalho,
        name="periodo_teletrabalho",
    ),
    path(
        "periodo-teletrabalho/delete/<int:pk>",
        views.periodo_teletrabalho_delete,
        name="periodo_teletrabalho_delete",
    ),
    # atividades teletrabalho
    path(
        "atividade-teletrabalho/<int:pk>",
        views.atividade_teletrabalho,
        name="atividade_teletrabalho",
    ),
    path(
        "atividade-teletrabalho/delete/<int:pk>",
        views.atividade_teletrabalho_delete,
        name="atividade_teletrabalho_delete",
    ),
    path(
        "atividade-cumprimento/<int:pk_avaliacao>/<int:pk_atividade>/<str:cumprimento>",
        views.atividade_cumprimento,
        name="atividade_cumprimento",
    ),
    # autorizacoes excecoes chefias
    path(
        "autorizacoes-excecoes/",
        views.autorizacoes_excecoes,
        name="autorizacoes_excecoes",
    ),
    path(
        "autorizacao-excecao/edit/<int:pk>",
        views.autorizacao_excecao_edit,
        name="autorizacao_excecao_edit",
    ),
    path(
        "autorizacao-excecao/delete/<int:pk>",
        views.autorizacao_excecao_delete,
        name="autorizacao_excecao_delete",
    ),
    # cigt
    path("cigt/", views.cigt, name="cigt"),
    path(
        "cigt/analisar-planos-trabalho",
        views.cigt_analisar_planos_trabalho,
        name="cigt_analisar_planos_trabalho",
    ),
    path(
        "cigt/analisar-protocolos-autorizacao",
        views.cigt_analisar_protocolos_autorizacao,
        name="cigt_analisar_protocolos_autorizacao",
    ),
    path(
        "cigt/analisar-avaliacoes-mensais",
        views.cigt_analisar_avaliacoes_mensais,
        name="cigt_analisar_avaliacoes_mensais",
    ),
    path(
        "cigt/controle-mensal-teletrabalho",
        views.cigt_controle_mensal_teletrabalho,
        name="cigt_controle_mensal_teletrabalho",
    ),
    path("cigt/portarias-doe", views.cigt_portarias_doe, name="cigt_portarias_doe"),
    path(
        "cigt/portarias-doe/<int:pk>",
        views.cigt_portaria_doe_edit,
        name="cigt_portaria_doe_edit",
    ),
    path(
        "cigt/download-portarias-doe/<int:pk>",
        views.download_portaria_doe,
        name="download_portaria_doe",
    ),
    path("avaliacoes-cigt/", views.avaliacoes_cigt, name="avaliacoes_cigt"),
    path(
        "encaminhar-avaliacoes-cigt/",
        views.encaminhar_avaliacoes_cigt,
        name="encaminhar_avaliacoes_cigt",
    ),
    path(
        "verificar-retorno-avaliacoes-cigt/",
        views.verificar_retorno_avaliacoes_cigt,
        name="verificar_retorno_avaliacoes_cigt",
    ),
    path("gerar_portaria_doe/", views.gerar_portaria_doe, name="gerar_portaria_doe"),
    # protocolos autotorizacao teletrabalho
    path(
        "protocolos-autorizacao-teletrabalho/",
        views.protocolos_autorizacao_teletrabalho,
        name="protocolos_autorizacao_teletrabalho",
    ),
    path(
        "protocolo-autorizacao-teletrabalho/edit/<int:pk>",
        views.protocolo_autorizacao_teletrabalho_edit,
        name="protocolo_autorizacao_teletrabalho_edit",
    ),
    # servidor
    path("servidor/", views.servidor, name="servidor"),
    path("servidor-avaliacoes/", views.servidor_avaliacoes, name="servidor_avaliacoes"),
    path(
        "servidor-avaliacao-atividades-list/<int:pk>",
        views.servidor_avaliacao_atividades_list,
        name="servidor_avaliacao_atividades_list",
    ),
    # chefia imediata
    path("chefia-imediata/", views.chefia_imediata, name="chefia_imediata"),
    # avaliar manifestacoes interesse
    path(
        "chefia-imediata-manifestacoes-interesse/",
        views.chefia_imediata_analisar_manifestacoes,
        name="chefia_imediata_analisar_manifestacoes",
    ),
    # avaliar planos de trabalho
    path(
        "chefia-imediata-planos-trabalho/",
        views.chefia_imediata_analisar_planos_trabalho,
        name="chefia_imediata_analisar_planos_trabalho",
    ),
    # realizar avaliacoes mensais
    path(
        "chefia-imediata-avaliacoes-mensais/",
        views.chefia_imediata_realizar_avaliacoes_mensais,
        name="chefia_imediata_realizar_avaliacoes_mensais",
    ),
    # avaliacoes chefia imediata
    path("avaliacoes-chefia/", views.avaliacoes_chefia, name="avaliacoes_chefia"),
    path(
        "avaliacoes-chefia/edit/<int:pk>",
        views.avaliacao_chefia_edit,
        name="avaliacao_chefia_edit",
    ),
    path(
        "avaliacao-atividades-list/<int:pk>",
        views.avaliacao_atividades_list,
        name="avaliacao_atividades_list",
    ),
    path(
        "avaliacao-chefia-atividade/<int:pk>",
        views.avaliacao_chefia_atividade,
        name="avaliacao_chefia_atividade",
    ),
    path(
        "avaliacao-chefia-atividade/finalizar/<int:pk>",
        views.finalizar_avaliacao,
        name="finalizar_avaliacao",
    ),
    path(
        "avaliacao-chefia-alterar/<int:pk>",
        views.chefia_imediata_alterar_avaliacao_mensal,
        name="chefia_imediata_alterar_avaliacao_mensal",
    ),
    # chefia imediata controle mensal teletrabalho
    path(
        "chefia-controle-mensal-teletrabalho/",
        views.chefia_imediata_controle_mensal,
        name="chefia_imediata_controle_mensal",
    ),
    # chefia imediata controle mensal teletrabalho cancela periodo
    path(
        "chefia-imediata-controle-mensal-cancelar_periodo/<int:pk>",
        views.chefia_imediata_controle_mensal_cancelar_periodo,
        name="chefia_imediata_controle_mensal_cancelar_periodo",
    ),
    # gabinete
    path("gabinete/", views.gabinete, name="gabinete"),
    # download arquivos
    path("download/<str:model>/<int:pk>", views.download_docx, name="download_docx"),
    # htmx
    path(
        "htmx-adiciona-periodo/",
        views.htmx_adiciona_periodo,
        name="htmx_adiciona_periodo",
    ),
    path(
        "htmx-adiciona-periodo-edit/<int:pk>",
        views.htmx_adiciona_periodo_edit,
        name="htmx_adiciona_periodo_edit",
    ),
    path(
        "htmx-adiciona-atividade",
        views.htmx_adiciona_atividade,
        name="htmx_adiciona_atividade",
    ),
    path(
        "htmx-adiciona-atividade-edit/<int:pk>",
        views.htmx_adiciona_atividade_edit,
        name="htmx_adiciona_atividade_edit",
    ),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/templates/webapp/pages/atividades-teletrabalho-form.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2>Atividades Teletrabalho</h2>

{{ request.user.name }}

<form method="POST">
    {% csrf_token %}
    {{ form }}    
    <input type="submit" value="SALVAR">

</form>

{% endblock%}

webapp/templates/webapp/pages/avaliacao-chefia-form.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2>Avaliação Chefia Imediata</h2>

<ul>
    {% for atividade in atividades_para_avaliacao %}
        <li>{{ atividade }}</li>
    {% endfor %}
</ul>
<br>
{{ formset }}
<br>
<ul>
    {{ avaliacao }} - {{ avaliacao.encaminhamento_avaliacao_cigt.ano_avaliacao }}/{{ avaliacao.encaminhamento_avaliacao_cigt.mes_avaliacao }}
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="SALVAR">
    </form>
</ul>

{% endblock%}

webapp/templates/webapp/pages/chefia-imediata-alterar-avaliacao-form.html
{% extends 'webapp/base/base.html' %}

{% load static %}

{% block title%}Home{% endblock%}

{% block content %}

<h2 class="title is-2">Justificativa para alteração da Avaliação</h2>

<p>SERVIDOR: {{ avaliacao.encaminhamento_avaliacao_cigt.despacho_cigt.plano_trabalho.manifestacao.lotacao_servidor.servidor }} </p>
<p>ANO: {{ avaliacao.encaminhamento_avaliacao_cigt.ano_avaliacao }}</p>
<p>MÊS: {{ avaliacao.encaminhamento_avaliacao_cigt.mes_avaliacao }}</p>
<h3 class="title is-5">{{ atividade.atividade }}</h3>

<form method="POST">
    {% csrf_token %}

    <div class="field">
        <label class="label">Avaliação</label>
        <div class="control">
            <div class="select">{{ form.avaliacao_chefia }}</div>
        </div>
    </div>
    

    <div class="field">
        {{ form.justificativa }}
    </div>

    <div class="field">
        <div class="control">
            <button class="button is-light" onclick="reorderItems()">Salvar</button>
        </div>
    </div>

</form>

{% endblock%}

{% block js%}

    <script
        src="{% static 'webapp/js/main.js' %}"
        defer
    ></script>

{% endblock js %}

webapp/templates/webapp/pages/cigt-controle-mensal-teletrabalho.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2 class="title is-2">CIGT - Controle Mensal Teletrabalho </h2>

<table class="table is-striped is-hoverable">
    <thead>
        <tr>
            <th>ID</th>
            <th>Servidor</th>
            <th>Protocolo Autorização</th>
            <th>Competência</th>
            <th>Vigente</th>
            <th>Publicado DOE</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in controle_mensal_objs %}
            {% if not avaliacao.atestado_cumprimento_metas %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td><a href={% url "webapp:protocolo_autorizacao_teletrabalho_edit" obj.protocolo_autorizacao.pk %}>{{ obj.protocolo_autorizacao.despacho_cigt.plano_trabalho.manifestacao.lotacao_servidor.servidor.user.nome}}</a></td>
                    <td>{{ obj.protocolo_autorizacao.sid }}</td>
                    <td>{{ obj.competencia }}</td>
                    <td>{{ obj.vigente }}</td>
                    <td>{{ obj.publicado_doe }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>

{% endblock%}

webapp/templates/webapp/pages/cigt-portaria-doe-form.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

{% if tipo_form == 'create' %}

<h2 class="title is-2">Criar Manifestacão de Interesse</h2>

{% elif tipo_form == 'edit' %}

<h2 class="title is-2">Editar Manifestacão de Interesse</h2>

{{ request.user.name }}

{% endif %}

<form method="POST">
    {% csrf_token %}

    <div class="field">
        <label class="label">Ano (REPR)</label>
        <div class="control">
            {{ form.ano }}
        </div>
    </div>

    <div class="field">
        <label class="label">Número (REPR)</label>
        <div class="control">
            {{ form.numero }}
        </div>
    </div>

    <div class="field">
        <label class="label">Diretor (REPR)</label>
        <div class="control">
            {{ form.diretor_em_exercicio }}
        </div>
    </div>

    <div class="field">
        <label for="" class="label">Data de Publicação (DOE)</label>
            {{ form.data_publicacao }}
    </div>
    
    <div class="field">
        <div class="control">
            <button class="button is-light">Salvar</button>
        </div>
    </div>

</form>

{% endblock%}

webapp/templates/webapp/pages/cigt-portarias-doe.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}
<div class="content">

    <h2 class="title is-2">CIGT - Portarias DOE </h2>

    <div class="field">
        <div class="control">
            <button class="button is-light">
                <a href="{% url "webapp:gerar_portaria_doe" %}">Gerar Nova Portaria DOE</a>
            </button>
        </div>
    </div>

    
    
    <h3 class="title is-4">Portarias Geradas</h3>
    
    <table class="table is-striped is-hoverable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Ano (REPR)</th>
                <th>Número (REPR)</th>
                <th>Data Publicação (DOE)</th>
                <th>Inclusões?</th>
                <th>Exclusões?</th>
                <th>Editar</th>
                <th>Docx</th>
            </tr>
        </thead>
        <tbody>
            {% for portaria in portarias %}
                <tr>
                    <td>{{ portaria.id }}</td>
                    <td>{{ portaria.ano }}</td>
                    <td>{{ portaria.numero }}</td>
                    <td>{{ portaria.data_publicacao }}</td>
                    <td>{{ portaria.has_inclusoes }}</td>
                    <td>{{ portaria.has_exclusoes }}</td>
                    <td><a href="{% url 'webapp:cigt_portaria_doe_edit' portaria.pk %}">{% if portaria.data_publicacao %}EDITAR{% else %}CADASTRAR DOE{% endif %}</a></td>
                    <td><a href="{% url 'webapp:download_portaria_doe' portaria.pk %}">{% if portaria.docx %}Baixar{% else %}[-]{% endif %}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    
    
</div>

{% endblock %}

webapp/templates/webapp/pages/cigt.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2 class="title is-2">CIGT</h2>

{% endblock%}

webapp/templates/webapp/pages/dados-cadastrais.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2 class="title is-2">Dados Cadastrais</h2>

<div class="field">
    <label for="" class="label">Grupos do Usuário</label>
    {% for group in user_groups %}{{ group.name }} | {% endfor %}
</div>

<div class="field">
    <label class="label">Nome</label>
    <div class="control">
        <input type="text" class="input" value="{{ request.user.nome}}" disabled>
    </div>
</div>

<div class="field">
    <label class="label">CPF</label>
    <div class="control">
        <input type="text" class="input" value="{{ request.user.username}}" disabled>
    </div>
</div>

<div class="field">
    <label class="label">RG</label>
    <div class="control">
        <input type="text" class="input" value="{{ request.user.rg}}" disabled>
    </div>
</div>

<form method="POST">
    {% csrf_token %}

    <div class="field">
        <label class="label">Usuário</label>
        <div class="control">
            <div class="select">{{ form_servidor.user }}</div>
        </div>
    </div>

    <div class="field">
        <label class="label">Cargo</label>
        <div class="control">
            <div class="select">{{ form_servidor.cargo }}</div>
        </div>
    </div>

    <div class="field">
        <label class="label">Lotação Atual</label>
        <p>Data Início: {{ ultima_lotacao.data_inicio }}</p>
        <p>Data Fim: {{ ultima_lotacao.data_fim }}</p>
        <p>Posto de Trabalho: {{ ultima_lotacao.posto_trabalho }}</p>
    </div>

    <div class="field">
        <label for="" class="label">Ramal</label>
        <div class="control">
            {{ form_servidor.ramal }}
        </div>
        {% if not form_servidor.ramal.initial %}
            <p class="help is-danger">Preencha esse campo!</p>
        {% endif %}
    </div>

    <div class="field">
        <label for="" class="label">Celular</label>
        <div class="control">
            {{ form_servidor.celular }}
        </div>
        {% if not form_servidor.celular.initial %}
            <p class="help is-danger">Preencha esse campo!</p>
        {% endif %}
    </div>

    <div class="field">
        <label for="" class="label">E-mail</label>
        <div class="control">
            {{ form_servidor.email }}
        </div>
        {% if not form_servidor.email.initial %}
            <p class="help is-danger">Preencha esse campo!</p>
        {% endif %}
    </div>

    <div class="field">
        <label for="" class="label">Cidade</label>
        <div class="control">
            {{ form_servidor.cidade }}
        </div>
        {% if not form_servidor.cidade.initial %}
            <p class="help is-danger">Preencha esse campo!</p>
        {% endif %}
    </div>

    <div class="field">
        <div class="control">
            <button class="button is-light">Atualizar</button>
        </div>
    </div>

</form>

{% endblock%}

webapp/templates/webapp/pages/encaminhar-avaliacoes-cigt.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2>Avaliações Encaminhadas</h2>
<ul>
    {% for avaliacao in avaliacoes_encaminhadas %}
        <li>{{ avaliacao.encaminhamento_avaliacao_cigt.ano_avaliacao }}/{{ avaliacao.encaminhamento_avaliacao_cigt.mes_avaliacao }} - {{ avaliacao }}</li>    
    {% endfor %}
</ul>

{% endblock%}

webapp/templates/webapp/pages/gabinete.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2>Gabinete</h2>

<h3><a href="{% url 'webapp:autorizacoes_excecoes' %}">Autorizações Exceções</a></h3>

{% endblock%}

webapp/templates/webapp/pages/periodo-teletrabalho-form.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2>Período Teletrabalho</h2>

{{ request.user.name }}

<form method="POST">
    {% csrf_token %}
    {{ form }}    
    <input type="submit" value="SALVAR">

</form>

{% endblock%}

webapp/templates/webapp/pages/plano-trabalho-aprovado-cigt.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}


<h2 class="title is-2">CIGT - Analisar Plano de Trabalho</h2>

    <div class="field">
        <label class="label">Manifestação de Interesse</label>
        <div class="control">
            <div class="select">{{ form_instance.manifestacao }}</div>
        </div>
    </div>

    <div class="field">
        <label class="label">Período de Comparecimento</label>
        <div class="control">
            {{ form_instance.periodo_comparecimento }}
        </div>
    </div>

    <div class="field">
        <label class="label">Período de Acionamento</label>
        <div class="control">
            {{ form_instance.periodo_acionamento }}
        </div>
    </div>

    <div class="field">
        <label class="label">Sistemas</label>
        <div class="control">
          <div class="select is-multiple">{{ form_instance.sistemas }}</div>
        </div>
      </div>

    <h4 class="title is-6">Período(s)</h4>

    <hr>
    
    {% for periodo in periodos_teletrabalho %}
        <p><a href="{% url 'webapp:periodo_teletrabalho' periodo.pk %}">{{ periodo }} plano_trabalho_id: {{ periodo.plano_trabalho_id }} período_id: {{ periodo.id}}</a> - <a href="{% url 'webapp:periodo_teletrabalho_delete' periodo.pk %}">excluir</a></p>
        {% endfor %}

    <hr>

    <h4 class="title is-6">Atividades</h4>

    {% for atividade in atividades_teletrabalho %}
    <p><a href="{% url 'webapp:atividade_teletrabalho' atividade.pk %}">{{ atividade }} - período_id: {{ atividade.periodo_id }} - atividade_id {{ atividade.id }}</a> - <a href="{% url 'webapp:atividade_teletrabalho_delete' atividade.pk %}">excluir</a></p>
    {% endfor %}

    <hr>
    <form method="POST">
        {% csrf_token %}

        <div class="field">
            <label class="label">Aprovado</label>
            <div class="control">
                <div class="select">{{ form.aprovado_cigt }}</div>
            </div>
        </div>
        
        <div class="field">
            <div class="control">
                <button class="button is-light">Salvar</button>
            </div>
        </div>

    </form>

{% endblock%}

webapp/templates/webapp/pages/plano-trabalho.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<div class="content">

    <h2 class="title is-2">Plano de Trabalho </h2>
    
    <h3 class="title is-4">Planos de Trabalho Cadastrados</h3>
    
    <table class="table is-striped is-hoverable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Servidor</th>
                <th>Aprovado (Chefia)</th>
                <th>Aprovado (CIGT)</th>
                <th>Editar</th>
                <th>Deletar</th>
            </tr>
        </thead>
        <tbody>
            {% for plano_trabalho in planos_trabalho %}
                <tr>
                    <td><a href={% url "webapp:download_docx" "plano-trabalho" plano_trabalho.id %}>{{ plano_trabalho.id }}</a></td>
                    <td>{{ plano_trabalho.manifestacao.lotacao_servidor.servidor }}</td>
                    <td>{% if plano_trabalho.aprovado_chefia == 'aprovado' %}SIM{% elif plano_trabalho.aprovado_chefia == 'reprovado' %}NÃO{% else %}PENDENTE{% endif %}</td>
                    <td>{% if plano_trabalho.aprovado_cigt == 'aprovado' %}SIM{% elif plano_trabalho.aprovado_cigt == 'reprovado' %}NÃO{% else %}PENDENTE{% endif %}</td>
                    <td><a href="{% url 'webapp:plano_trabalho_edit' plano_trabalho.pk %}">{% if plano_trabalho.aprovado_chefia%}[X]{% else %}editar{% endif %}</a></td>
                    <td><a href="{% url 'webapp:plano_trabalho_delete' plano_trabalho.pk %}">{% if plano_trabalho.aprovado_chefia%}[X]{% else %}deletar{% endif %}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a href="{% url 'webapp:plano_trabalho_create' %}" class="button">[+] Cadastrar Plano de Trabalho</a>
    
</div>

{% endblock%}

webapp/templates/webapp/pages/protocolo-autorizacao-teletrabalho-form.html
{% extends 'webapp/base/base.html' %}

{% block title%}Home{% endblock%}

{% block content %}

<h2>Protocolo de Autorização do Teletrabalho</h2>

<div class="field">
    <label class="label">Despacho CIGT</label>
    <div class="control">
        <div class="select">{{ form_instance.despacho_cigt }}</div>
    </div>
</div>

<form method="POST">
    {% csrf_token %}
    
    <div class="field">
        <label class="label">Protocolo (SID)</label>
        <div class="control">
            {{ form.sid }}
        </div>
    </div>

    <div class="field">
        <label class="label">Publicado DOE</label>
        <div class="control">
            <div class="select">{{ form.publicado_doe }}</div>
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <button class="button is-light">Salvar</button>
        </div>
    </div>

</form>

{% endblock%}