authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout_view'),
    path('password_change/', views.password_change, name='password_change'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('home/', include('webapp.urls')),
    path('media/<path:path>', views.secure_media, name='secure_media'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from . import views

app_name = "webapp"

urlpatterns = [
    path("", views.home, name="home"),
    # dados-cadastrais
    path("dados-cadastrais/", views.dados_cadastrais, name="dados_cadastrais"),
    # manifestacao-interesse
    path(
        "manifestacao-interesse/",
        views.manifestacao_interesse,
        name="manifestacao_interesse",
    ),
    path(
        "manifestacao-interesse/create",
        views.manifestacao_interesse_create,
        name="manifestacao_interesse_create",
    ),
    path(
        "manifestacao-interesse/chefia/<int:pk>/",
        views.manifestacao_interesse_aprovado_chefia,
        name="manifestacao_interesse_aprovado_chefia",
    ),
    path(
        "manifestacao-interesse/delete/<int:pk>/",
        views.manifestacao_interesse_delete,
        name="manifestacao_interesse_delete",
    ),
    # declaracao-nao-enquadramento-nas-vedacoes
    path(
        "declaracao-nao-enquadramento/",
        views.declaracao_nao_enquadramento,
        name="declaracao_nao_enquadramento",
    ),
    path(
        "declaracao-nao-enquadramento-create/",
        views.declaracao_nao_enquadramento_create,
        name="declaracao_nao_enquadramento_create",
    ),
    # plano-de-trabalho
    path("plano-trabalho/", views.plano_trabalho, name="plano_trabalho"),
    path(
        "plano-trabalho/create/",
        views.plano_trabalho_create,
        name="plano_trabalho_create",
    ),
    path(
        "plano-trabalho/edit/<int:pk>",
        views.plano_trabalho_edit,
        name="plano_trabalho_edit",
    ),
    path(
        "plano-trabalho/chefia/<int:pk>/",
        views.plano_trabalho_aprovado_chefia,
        name="plano_trabalho_aprovado_chefia",
    ),
    path(
        "plano-trabalho/cigt/<int:pk>/",
        views.plano_trabalho_aprovado_cigt,
        name="plano_trabalho_aprovado_cigt",
    ),
    path(
        "plano-trabalho/delete/<int:pk>",
        views.plano_trabalho_delete,
        name="plano_trabalho_delete",
    ),
    # periodo teletrabalho
    path(
        "periodo-teletrabalho/<int:pk>",
        views.periodo_teletrabalho,
        name="periodo_teletrabalho",
    ),
    path(
        "periodo-teletrabalho/delete/<int:pk>",
        views.periodo_teletrabalho_delete,
        name="periodo_teletrabalho_delete",
    ),
    # atividades teletrabalho
    path(
        "atividade-teletrabalho/<int:pk>",
        views.atividade_teletrabalho,
        name="atividade_teletrabalho",
    ),
    path(
        "atividade-teletrabalho/delete/<int:pk>",
        views.atividade_teletrabalho_delete,
        name="atividade_teletrabalho_delete",
    ),
    path(
        "atividade-cumprimento/<int:pk_avaliacao>/<int:pk_atividade>/<str:cumprimento>",
        views.atividade_cumprimento,
        name="atividade_cumprimento",
    ),
    # autorizacoes excecoes chefias
    path(
        "autorizacoes-excecoes/",
        views.autorizacoes_excecoes,
        name="autorizacoes_excecoes",
    ),
    path(
        "autorizacao-excecao/edit/<int:pk>",
        views.autorizacao_excecao_edit,
        name="autorizacao_excecao_edit",
    ),
    path(
        "autorizacao-excecao/delete/<int:pk>",
        views.autorizacao_excecao_delete,
        name="autorizacao_excecao_delete",
    ),
    # cigt
    path("cigt/", views.cigt, name="cigt"),
    path(
        "cigt/analisar-planos-trabalho",
        views.cigt_analisar_planos_trabalho,
        name="cigt_analisar_planos_trabalho",
    ),
    path(
        "cigt/analisar-protocolos-autorizacao",
        views.cigt_analisar_protocolos_autorizacao,
        name="cigt_analisar_protocolos_autorizacao",
    ),
    path(
        "cigt/analisar-avaliacoes-mensais",
        views.cigt_analisar_avaliacoes_mensais,
        name="cigt_analisar_avaliacoes_mensais",
    ),
    path(
        "cigt/controle-mensal-teletrabalho",
        views.cigt_controle_mensal_teletrabalho,
        name="cigt_controle_mensal_teletrabalho",
    ),
    path("cigt/portarias-doe", views.cigt_portarias_doe, name="cigt_portarias_doe"),
    path(
        "cigt/portarias-doe/<int:pk>",
        views.cigt_portaria_doe_edit,
        name="cigt_portaria_doe_edit",
    ),
    path(
        "cigt/download-portarias-doe/<int:pk>",
        views.download_portaria_doe,
        name="download_portaria_doe",
    ),
    path("avaliacoes-cigt/", views.avaliacoes_cigt, name="avaliacoes_cigt"),
    path(
        "encaminhar-avaliacoes-cigt/",
        views.encaminhar_avaliacoes_cigt,
        name="encaminhar_avaliacoes_cigt",
    ),
    path(
        "verificar-retorno-avaliacoes-cigt/",
        views.verificar_retorno_avaliacoes_cigt,
        name="verificar_retorno_avaliacoes_cigt",
    ),
    path("gerar_portaria_doe/", views.gerar_portaria_doe, name="gerar_portaria_doe"),
    # protocolos autotorizacao teletrabalho
    path(
        "protocolos-autorizacao-teletrabalho/",
        views.protocolos_autorizacao_teletrabalho,
        name="protocolos_autorizacao_teletrabalho",
    ),
    path(
        "protocolo-autorizacao-teletrabalho/edit/<int:pk>",
        views.protocolo_autorizacao_teletrabalho_edit,
        name="protocolo_autorizacao_teletrabalho_edit",
    ),
    # servidor
    path("servidor/", views.servidor, name="servidor"),
    path("servidor-avaliacoes/", views.servidor_avaliacoes, name="servidor_avaliacoes"),
    path(
        "servidor-avaliacao-atividades-list/<int:pk>",
        views.servidor_avaliacao_atividades_list,
        name="servidor_avaliacao_atividades_list",
    ),
    # chefia imediata
    path("chefia-imediata/", views.chefia_imediata, name="chefia_imediata"),
    # avaliar manifestacoes interesse
    path(
        "chefia-imediata-manifestacoes-interesse/",
        views.chefia_imediata_analisar_manifestacoes,
        name="chefia_imediata_analisar_manifestacoes",
    ),
    # avaliar planos de trabalho
    path(
        "chefia-imediata-planos-trabalho/",
        views.chefia_imediata_analisar_planos_trabalho,
        name="chefia_imediata_analisar_planos_trabalho",
    ),
    # realizar avaliacoes mensais
    path(
        "chefia-imediata-avaliacoes-mensais/",
        views.chefia_imediata_realizar_avaliacoes_mensais,
        name="chefia_imediata_realizar_avaliacoes_mensais",
    ),
    # avaliacoes chefia imediata
    path("avaliacoes-chefia/", views.avaliacoes_chefia, name="avaliacoes_chefia"),
    path(
        "avaliacoes-chefia/edit/<int:pk>",
        views.avaliacao_chefia_edit,
        name="avaliacao_chefia_edit",
    ),
    path(
        "avaliacao-atividades-list/<int:pk>",
        views.avaliacao_atividades_list,
        name="avaliacao_atividades_list",
    ),
    path(
        "avaliacao-chefia-atividade/<int:pk>",
        views.avaliacao_chefia_atividade,
        name="avaliacao_chefia_atividade",
    ),
    path(
        "avaliacao-chefia-atividade/finalizar/<int:pk>",
        views.finalizar_avaliacao,
        name="finalizar_avaliacao",
    ),
    path(
        "avaliacao-chefia-alterar/<int:pk>",
        views.chefia_imediata_alterar_avaliacao_mensal,
        name="chefia_imediata_alterar_avaliacao_mensal",
    ),
    # chefia imediata controle mensal teletrabalho
    path(
        "chefia-controle-mensal-teletrabalho/",
        views.chefia_imediata_controle_mensal,
        name="chefia_imediata_controle_mensal",
    ),
    # chefia imediata controle mensal teletrabalho cancela periodo
    path(
        "chefia-imediata-controle-mensal-cancelar_periodo/<int:pk>",
        views.chefia_imediata_controle_mensal_cancelar_periodo,
        name="chefia_imediata_controle_mensal_cancelar_periodo",
    ),
    # gabinete
    path("gabinete/", views.gabinete, name="gabinete"),
    # download arquivos
    path("download/<str:model>/<int:pk>", views.download_docx, name="download_docx"),
    # htmx
    path(
        "htmx-adiciona-periodo/",
        views.htmx_adiciona_periodo,
        name="htmx_adiciona_periodo",
    ),
    path(
        "htmx-adiciona-periodo-edit/<int:pk>",
        views.htmx_adiciona_periodo_edit,
        name="htmx_adiciona_periodo_edit",
    ),
    path(
        "htmx-adiciona-atividade",
        views.htmx_adiciona_atividade,
        name="htmx_adiciona_atividade",
    ),
    path(
        "htmx-adiciona-atividade-edit/<int:pk>",
        views.htmx_adiciona_atividade_edit,
        name="htmx_adiciona_atividade_edit",
    ),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/templates/webapp/partials/add_atividade.html
<div id="atividade-{{ forloop.counter0 }}">
    <div class="field">
        {{ form.periodo }}
    </div>
    
    <div class="field">
        <label class="label">Atividade</label>
        <div class="control">
            <div class="select">{{ form.atividade }}</div>
        </div>
    </div>

    <div class="field">
        <label for="" class="label">Meta Qualitativa</label>
        <div class="control">
            {{ form.meta_qualitativa }}
        </div>
    </div>

    <div class="field">
        <label class="label">Tipo de Meta Quantitativa</label>
        <div class="control">
            <div class="select">{{ form.tipo_meta_quantitativa }}</div>
        </div>
    </div>

    <div class="field">
        <label for="" class="label">Meta Quantitativa</label>
        <div class="control">
            {{ form.meta_quantitativa }}
        </div>
</div>

webapp/templates/webapp/partials/add_atividade_edit.html
{% for atividade in atividades_teletrabalho %}
    <p><a href="{% url 'webapp:atividade_teletrabalho' atividade.pk %}">{{ atividade }} - período_id: {{ atividade.periodo_id }} - atividade_id {{ atividade.id }}</a> - <a href="{% url 'webapp:atividade_teletrabalho_delete' atividade.pk %}">excluir</a></p>
{% endfor %}

webapp/templates/webapp/partials/add_periodo.html
<div id="periodo-{{ forloop.counter0 }}">

    <div class="field">
        {{ form.plano_trabalho }}
    </div>

    <div class="field">
        <label class="label">Data Inicial</label>
        {{ form.data_inicio }}
    </div>

    <div class="field">
        <label class="label">Data Final</label>
        <div class="control">
        {{ form.data_fim }}
        </div>
    </div>
</div>

webapp/templates/webapp/partials/add_periodo_atividade_edit.html
<div id="periodos-atividades-edit" class="periodos-atividades-edit">
{% for periodo in periodos_teletrabalho %}
    <p><a href="{% url 'webapp:periodo_teletrabalho' periodo.pk %}">{{ periodo }} plano_trabalho_id: {{ periodo.plano_trabalho_id }} período_id: {{ periodo.id}}</a> - <a href="{% url 'webapp:periodo_teletrabalho_delete' periodo.pk %}">excluir</a></p>
{% endfor %}

<hr>

<h3 class="title is-5"> Atividades </h3>
{% for atividade in atividades_teletrabalho %}
<p><a href="{% url 'webapp:atividade_teletrabalho' atividade.pk %}">{{ atividade }} - período_id: {{ atividade.periodo_id }} - atividade_id {{ atividade.id }}</a> - <a href="{% url 'webapp:atividade_teletrabalho_delete' atividade.pk %}">excluir</a></p>
{% endfor %}
</div>

webapp/templates/webapp/partials/add_periodo_edit.html
    {% for periodo in periodos_teletrabalho %}
        <p><a href="{% url 'webapp:periodo_teletrabalho' periodo.pk %}">{{ periodo }} plano_trabalho_id: {{ periodo.plano_trabalho_id }} período_id: {{ periodo.id}}</a> - <a href="{% url 'webapp:periodo_teletrabalho_delete' periodo.pk %}">excluir</a></p>
    {% endfor %}

webapp/templates/webapp/partials/footer.html
<footer class="footer">
    <div class="content has-text-centered">
        <p>Receita Estadual do Paraná <strong>(REPR)</strong></p>
        <p>Comissão Interna de Gestão do Teletrabalho (<strong>CIGT</strong>)</p>
        <p>Sistema de Controle do Teletrabalho (<strong>SISCOT</strong>)</p> 
    </div>
  </footer>

webapp/templates/webapp/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'webapp/css/styles.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<script src="https://unpkg.com/htmx.org@1.9.11" integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0" crossorigin="anonymous"></script>

webapp/templates/webapp/partials/header.html
<nav class="navbar is-transparent">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://127.0.0.1:8000/home/">
        SISCOT
      </a>
      <div class="navbar-burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link" href="{% url 'webapp:servidor' %}">
            Servidor
          </a>
          <div class="navbar-dropdown is-boxed">
            <a class="navbar-item" href="{% url 'webapp:dados_cadastrais' %}">
              Dados Cadastrais
            </a>
            <a class="navbar-item" href="{% url 'webapp:manifestacao_interesse' %}">
              Manifestação de Interesse
            </a>
            <a class="navbar-item" href="{% url 'webapp:declaracao_nao_enquadramento' %}">
              Declaração de Não Enquadramento nas Vedações
            </a>
            <a class="navbar-item" href="{% url 'webapp:plano_trabalho' %}">
              Planos de Trabalho
            </a>
            <a class="navbar-item" href="{% url 'webapp:servidor_avaliacoes' %}">
              Avaliações da Chefia
            </a>
          </div>
        </div>
      </div>
      {% if 'CHEFIAS' in request.user.get_group_set %}
      <div class="navbar-start">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link" href="{% url 'webapp:chefia_imediata' %}">
            Chefia Imediata
          </a>
          <div class="navbar-dropdown is-boxed">

            <a class="navbar-item" href="{% url 'webapp:chefia_imediata_analisar_manifestacoes' %}">
              Analisar Manifestações de Interesse
            </a>
            <a class="navbar-item" href="{% url 'webapp:chefia_imediata_analisar_planos_trabalho' %}">
              Analisar Planos de Trabalho
            </a>
            <a class="navbar-item" href="{% url 'webapp:chefia_imediata_realizar_avaliacoes_mensais' %}">
              Realizar Avaliações Mensais
            </a>
            <a class="navbar-item" href="{% url 'webapp:chefia_imediata_controle_mensal' %}">
              Controle Mensal Teletrabalho
            </a>
          </div>
        </div>
      </div>
      {% endif %}

      {% if 'GABINETE' in request.user.get_group_set %}
      <div class="navbar-start">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link" href="{% url 'webapp:gabinete' %}">
            Gabinete REPR
          </a>
          <div class="navbar-dropdown is-boxed">
            <a class="navbar-item" href="{% url 'webapp:autorizacoes_excecoes' %}">
              Analisar Solicitações das Chefias Imediatas
            </a>
          </div>
        </div>
      </div>
      {% endif %}

      {% if 'CIGT' in request.user.get_group_set %}
      <div class="navbar-start">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link" href="{% url 'webapp:cigt' %}">
            CIGT
          </a>
          <div class="navbar-dropdown is-boxed">
            <a class="navbar-item" href="{% url 'webapp:cigt_analisar_planos_trabalho' %}">
              Analisar Planos de Trabalho
            </a>
            <a class="navbar-item" href="{% url 'webapp:cigt_analisar_protocolos_autorizacao' %}">
                Protocolos de Autorização
            </a>
            <a class="navbar-item" href="{% url 'webapp:cigt_portarias_doe' %}">
                Portarias DOE
            </a>
            <a class="navbar-item" href="{% url 'webapp:cigt_analisar_avaliacoes_mensais' %}">
                Analisar Avaliações Mensais
            </a>
            <a class="navbar-item" href="{% url 'webapp:cigt_controle_mensal_teletrabalho' %}">
                Controle Mensal Teletrabalho
            </a>
          </div>
        </div>
      </div>
      {% endif %}
  
      <div class="navbar-end">
        <div class="navbar-item">
          <small>[ logado: {{ request.user.username }} ]</small>
      </div>
      <div class="buttons">
          <a class="button is-light"
          href="{% url 'authentication:logout_view' %}">
          Logout
          </a>
      </div>
      </div>
    </div>
  </nav>